### ISSUE TITLE
`dropExtraColumns` argument request in `validateCohortArgument` 

### ISSUE THREAD

**Issue by nmercadeb** [darwin-eu/omopgenerics#526]
This argument would be helpful for CohortConstructor, see current internal function below:
https://github.com/OHDSI/CohortConstructor/blob/5c2144acd9ca8ad3323bd14af4943fbfe81d0d31/R/validateFunctions.R#L15

**Comment by nmercadeb** [comment]
Also, what would you think of having an argument indicating whether temporal tables are allowed? I knowaren't supposed to be temporal but currently the code below is crushing due to this, and maybe would be nice to allow it to work?

```
#' library(CohortConstructor)
#' library(PatientProfiles)
#'
#' cdm <- mockCohortConstructor()
#'
#' cdm$my_cohort <- cdm$cohort1 |>
#'   addAge(ageGroup = list("child" = c(0, 17), "adult" = c(18, Inf))) |>
#'   addSex() |>
#'   stratifyCohorts(
#'     strata = list("sex", c("sex", "age_group")), name = "my_cohort"
#'   )
```

**Comment by catalamarti** [comment]
I am happy to add the dropExtraColumns argument because it can be useful, but I don't see why the current behaviour makes your reprex to crash, in principle the current behaviour is that no column is droped

**Comment by nmercadeb** [comment]
At that moment I think it wasn't working because the cohort table was not a permanent table
