### ISSUE TITLE
require columns in settings are character?

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu/omopgenerics#536]
Getting this error from bind where two results have the column "cohort_definition_id" in settings, but one is integer and the other is character? I'm wondering if for all settings columns except result_id, they should just be required to be character? (and coerced to be with a warning if not)

```
Browse[1]> dataSubset %>% omopgenerics::bind()
Error in dplyr::bind_rows(lapply(results, settings), .id = "list_id") : 
  Can't combine `cohort_details_AurumCDM_202403$cohort_definition_id` <integer> and `cohort_details_OHDSI snowflake$cohort_definition_id` <character>.
```

**Comment by catalamarti** [comment]
So my long term plan was that if we store settings in long format in the format:
settings_name, settings_type, settings_value -> this would allow us to still bind settings with different types, and then the warning would appear when: settings.summarised_result is triggered and settings are pivoted.

What do you think @edward-burn ?
