### ISSUE TITLE
Add variable_level columns to checkGroup()

### ISSUE THREAD

**Issue by martaalcalde** [darwin-eu/omopgenerics#542]
![Image](https://github.com/user-attachments/assets/2a4eb24b-0238-44f5-bc65-7f25c8d36895)

**Comment by catalamarti** [comment]
If we add this, the validation no longer make sense. There are two options:
- We remove that validation -> we have to think how we do suppression then
- Your dataset structures differently (variable_name and variable_level interchange)

**Comment by martaalcalde** [comment]
Happy to reach an agreement, as this is breaking OmopSketch. Maybe I could move variable_level to additional_level, and in additional_name add "time_interval"? I think that, for consistency, I should change also other functions such as "summariseInObservation" or "summariseConceptCounts" though.
